spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        use_sql_comments: false
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver